-- Expands the exercise library and makes future seeding idempotent by name.
-- Run this in the Supabase SQL editor after 0001_init.sql.

alter table public.exercises add constraint exercises_name_key unique (name);

insert into public.exercises (name, muscle_group, equipment, description) values
  ('Front Squat', 'legs', 'Barbell', 'Quad-focused squat variation with a front-rack hold.'),
  ('Bulgarian Split Squat', 'legs', 'Dumbbells', 'Unilateral quad and glute builder.'),
  ('Leg Extension', 'legs', 'Machine', 'Quad isolation.'),
  ('Lying Leg Curl', 'legs', 'Machine', 'Hamstring isolation.'),
  ('Hip Thrust', 'legs', 'Barbell', 'Glute-focused hip extension.'),
  ('Goblet Squat', 'legs', 'Dumbbell', 'Beginner-friendly squat pattern.'),
  ('Seated Calf Raise', 'legs', 'Machine', 'Soleus-focused calf isolation.'),
  ('Hack Squat', 'legs', 'Machine', 'Quad-dominant machine squat.'),
  ('Glute Bridge', 'legs', 'Bodyweight', 'Glute activation and isolation.'),
  ('Step-Up', 'legs', 'Dumbbells', 'Unilateral leg and glute builder.'),
  ('Decline Barbell Press', 'chest', 'Barbell', 'Lower chest emphasis.'),
  ('Flat Dumbbell Press', 'chest', 'Dumbbells', 'Chest press with a longer range of motion.'),
  ('Incline Barbell Press', 'chest', 'Barbell', 'Upper chest emphasis.'),
  ('Dumbbell Fly', 'chest', 'Dumbbells', 'Chest isolation, stretch-focused.'),
  ('Pec Deck', 'chest', 'Machine', 'Chest isolation on a fixed path.'),
  ('Dips', 'chest', 'Bodyweight', 'Lower chest and triceps compound.'),
  ('Landmine Press', 'chest', 'Barbell', 'Shoulder-friendly angled chest press.'),
  ('Chin-Up', 'back', 'Bodyweight', 'Vertical pull with biceps emphasis.'),
  ('T-Bar Row', 'back', 'Barbell', 'Thick mid-back horizontal pull.'),
  ('Single-Arm Dumbbell Row', 'back', 'Dumbbell', 'Unilateral back builder.'),
  ('Face Pull', 'back', 'Cable', 'Rear delt and upper back health.'),
  ('Straight-Arm Pulldown', 'back', 'Cable', 'Lat isolation.'),
  ('Rack Pull', 'back', 'Barbell', 'Partial deadlift, upper back and traps.'),
  ('Chest-Supported Row', 'back', 'Machine', 'Strict horizontal pull, less lower-back load.'),
  ('Arnold Press', 'shoulders', 'Dumbbells', 'Rotational shoulder press hitting all three heads.'),
  ('Dumbbell Shoulder Press', 'shoulders', 'Dumbbells', 'Vertical push variation.'),
  ('Front Raise', 'shoulders', 'Dumbbells', 'Front delt isolation.'),
  ('Cable Lateral Raise', 'shoulders', 'Cable', 'Side delt isolation with constant tension.'),
  ('Upright Row', 'shoulders', 'Barbell', 'Traps and side delts.'),
  ('Shrug', 'shoulders', 'Dumbbells', 'Trap isolation.'),
  ('Preacher Curl', 'arms', 'Barbell', 'Strict biceps isolation.'),
  ('Concentration Curl', 'arms', 'Dumbbell', 'Peak-focused biceps isolation.'),
  ('Cable Curl', 'arms', 'Cable', 'Biceps isolation with constant tension.'),
  ('Overhead Tricep Extension', 'arms', 'Dumbbell', 'Long-head triceps emphasis.'),
  ('Close-Grip Bench Press', 'arms', 'Barbell', 'Triceps-focused pressing compound.'),
  ('Dumbbell Kickback', 'arms', 'Dumbbell', 'Triceps isolation.'),
  ('Russian Twist', 'core', 'Bodyweight', 'Rotational core work.'),
  ('Ab Wheel Rollout', 'core', 'Ab Wheel', 'Anti-extension core work under load.'),
  ('Side Plank', 'core', 'Bodyweight', 'Oblique and lateral core stability.'),
  ('Mountain Climber', 'core', 'Bodyweight', 'Dynamic core and hip flexor work.'),
  ('Sit-Up', 'core', 'Bodyweight', 'Classic ab flexion.'),
  ('Toes to Bar', 'core', 'Bodyweight', 'Advanced hanging ab movement.')
on conflict (name) do nothing;
