-- Adds a "why it's effective" field so the exercise detail page can explain the
-- training rationale behind each movement, not just how to perform it.
-- Run this in the Supabase SQL editor after 0001-0004.

alter table public.exercises add column if not exists why_effective text;

update public.exercises as e set why_effective = v.why_effective
from (values
  ('Barbell Curl', 'The fixed bar path lets both arms move together under one heavy load, so you can overload the biceps with more total weight than single-arm dumbbell work allows.'),
  ('Hammer Curl', 'The neutral, palms-in grip shifts emphasis onto the brachialis and brachioradialis, the muscles that add arm thickness and drive raw grip and pulling strength.'),
  ('Preacher Curl', 'Bracing the upper arm on the pad removes shoulder swing entirely, forcing the biceps to handle the full load from the deep, stretched bottom position where they''re usually weakest.'),
  ('Concentration Curl', 'Isolating one arm with the elbow braced against the leg removes all body english, producing a strict, full-stretch-to-full-squeeze biceps contraction.'),
  ('Cable Curl', 'Constant cable tension keeps the biceps loaded even near the top of the curl, unlike a dumbbell or barbell where tension drops off close to lockout.'),
  ('Tricep Pushdown', 'Constant cable tension and a fixed downward path isolate the triceps through full elbow extension with no shoulder assistance.'),
  ('Skull Crusher', 'Keeping the upper arms still and moving only at the elbow isolates the long head of the triceps through a deep, stretch-loaded range of motion.'),
  ('Overhead Tricep Extension', 'The overhead arm position pre-stretches the long head of the triceps across both the shoulder and elbow, loading the portion that pushdowns barely touch.'),
  ('Dumbbell Kickback', 'Extending the arm straight back puts peak tension on the triceps right at lockout, the exact point most pressing movements let the triceps coast through.'),
  ('Close-Grip Bench Press', 'Narrowing the grip shifts load off the chest and onto the triceps while still letting you press heavy compound weight for real triceps mass.'),
  ('Lateral Raise', 'Raising the arms out to the sides isolates the lateral deltoid, the head responsible for shoulder width, in a way pressing movements can''t reach.'),
  ('Cable Lateral Raise', 'Cable tension stays constant through the whole arc — unlike a dumbbell, which goes slack near the top — so the lateral delt stays loaded through its full range.'),
  ('Front Raise', 'Isolating shoulder flexion removes the triceps and chest contribution that presses normally rely on, putting the work squarely on the anterior deltoid.'),
  ('Rear Delt Fly', 'Horizontal abduction targets the posterior deltoid and upper back, a pairing that''s chronically undertrained relative to the front delts and chest in most programs.'),
  ('Face Pull', 'Pulling to the face with external rotation hits the rear delts and rotator cuff together, directly counteracting the internally-rotated shoulder posture that heavy pressing creates.'),
  ('Arnold Press', 'The rotating path takes the shoulder from internal to external rotation over the course of the rep, recruiting the anterior and lateral deltoid heads more completely than a standard press.'),
  ('Dumbbell Shoulder Press', 'Independent dumbbells let each shoulder find its own natural pressing groove, building overhead strength while demanding extra stabilizer work.'),
  ('Overhead Press', 'A strict vertical press on a fixed bar lets you overload the entire shoulder girdle and triceps with more weight than a dumbbell press allows.'),
  ('Upright Row', 'Pulling the bar up along the body combines a shrug with a raise, loading the lateral deltoid and upper traps together in one movement.'),
  ('Shrug', 'A pure scapular elevation movement that isolates the upper trapezius, the muscle that builds the neck-to-shoulder line.'),
  ('Landmine Press', 'The angled bar path lets you press heavy at a shoulder-friendly angle, biasing the upper chest without the wrist and shoulder strain of a flat barbell press.'),
  ('Incline Barbell Press', 'The upward bench angle shifts more load onto the clavicular (upper) head of the pec, the portion flat pressing tends to undertrain.'),
  ('Incline Dumbbell Press', 'Independent dumbbells at an incline target the upper chest while allowing a deeper stretch and more natural pressing arc than a fixed barbell.'),
  ('Decline Barbell Press', 'The downward angle shifts emphasis onto the lower chest fibers and shortens the range of motion, letting you handle heavier loads safely.'),
  ('Flat Dumbbell Press', 'Dumbbells allow a longer range of motion than a barbell and let each side of the chest work independently, exposing side-to-side strength imbalances.'),
  ('Barbell Bench Press', 'A stable bar path lets you move more total weight than any other pressing movement, making it the standard for raw chest, shoulder, and triceps strength.'),
  ('Dumbbell Fly', 'An arcing, elbows-fixed path isolates the pec major through a deep stretch that pressing movements — which recruit the triceps — can''t replicate.'),
  ('Cable Chest Fly', 'Constant cable tension keeps the pecs loaded through the entire arc, including full contraction at the finish where a dumbbell fly loses tension.'),
  ('Pec Deck', 'A fixed, supported path isolates the chest without triceps or stabilizer assistance, useful for pushing the pecs to failure safely.'),
  ('Dips', 'Leaning forward loads the lower chest and triceps with your own bodyweight through a deep stretch at the bottom of the movement.'),
  ('Push-Up', 'A bodyweight closed-chain press that trains the chest, shoulders, and triceps together while demanding core stability to keep the body rigid.'),
  ('Pull-Up', 'Pulling your own bodyweight vertically is one of the most effective builders of lat width, grip, and overall back strength there is.'),
  ('Chin-Up', 'The underhand grip recruits the biceps more heavily alongside the lats, making it a vertical pull with a built-in arm-strength bonus.'),
  ('Lat Pulldown', 'A machine-controlled vertical pull that trains the same lat-width movement pattern as a pull-up at a weight you can dial in and progress.'),
  ('Straight-Arm Pulldown', 'Keeping the arms straight isolates the lats through shoulder extension alone, removing the biceps that dominate rowing and pulldown movements.'),
  ('Barbell Row', 'A heavy hip-hinged pull that loads the entire back — lats, rhomboids, traps, rear delts — while the fixed bar lets you move serious weight.'),
  ('T-Bar Row', 'The chest-supported, close-grip setup lets you row heavy with a thick, neutral grip that emphasizes mid-back thickness and the rhomboids.'),
  ('Seated Cable Row', 'Constant horizontal cable tension builds mid-back thickness while the seated position removes lower-back involvement from the movement.'),
  ('Single-Arm Dumbbell Row', 'Working one side at a time lets you focus fully on that lat''s contraction and corrects side-to-side back imbalances.'),
  ('Chest-Supported Row', 'Bracing the chest on a pad removes all momentum and lower-back strain, isolating the back muscles through a strict pulling motion.'),
  ('Deadlift', 'A full hip-hinge that loads the posterior chain — hamstrings, glutes, spinal erectors, traps, and grip — more completely than any other single exercise.'),
  ('Rack Pull', 'Starting from knee height overloads the top-range lockout, building trap and upper-back strength with more weight than a full deadlift allows.'),
  ('Barbell Back Squat', 'A hip-and-knee-dominant squat that loads the quads, glutes, and adductors under a heavy axial load while forcing the core and spinal erectors to stabilize the entire lift.'),
  ('Romanian Deadlift', 'A hip-hinge with minimal knee bend that loads the hamstrings and glutes eccentrically at full stretch, training the exact position most other leg exercises skip.'),
  ('Leg Press', 'A fixed, supported path that overloads the quads and glutes with heavy weight without any lower-back stabilization demand.'),
  ('Walking Lunge', 'Unilateral loading under motion builds single-leg strength, balance, and glute activation that bilateral squats don''t train.'),
  ('Front Squat', 'Racking the bar on the front shoulders forces an upright torso, shifting more load onto the quads than a back squat while building the core and upper-back strength needed to hold the position.'),
  ('Bulgarian Split Squat', 'Elevating the rear foot puts nearly all the load on the front leg, building serious unilateral quad and glute strength while exposing side-to-side imbalances.'),
  ('Goblet Squat', 'Holding the weight at the chest counterbalances the squat, making it easier to keep an upright torso and hit depth — ideal for building the squat pattern.'),
  ('Hack Squat', 'The angled, back-supported machine path isolates the quads with heavy load while removing the balance and lower-back demand of a free squat.'),
  ('Step-Up', 'Driving up onto a box trains single-leg strength and glute activation through a full range of hip and knee extension.'),
  ('Leg Extension', 'An open-chain, single-joint movement that isolates the quads through full knee extension without any hip or hamstring involvement.'),
  ('Lying Leg Curl', 'Isolates the hamstrings through knee flexion alone, targeting a muscle group that most squat- and press-focused programs undertrain.'),
  ('Standing Calf Raise', 'Loading the calves with the knee straight targets the gastrocnemius through its full stretch-to-contraction range.'),
  ('Seated Calf Raise', 'Bending the knee takes the gastrocnemius out of play and shifts the load onto the soleus, the deeper calf muscle that needs a different angle to train.'),
  ('Hip Thrust', 'Driving the hips up against a loaded barbell puts the glutes in their strongest, most contracted position, making this the most direct heavy-load glute builder there is.'),
  ('Glute Bridge', 'A bodyweight or lightly-loaded hip extension that teaches glute activation and hip control without loading the spine.'),
  ('Sit-Up', 'A full spinal-flexion movement that trains the rectus abdominis through a longer range of motion than a crunch.'),
  ('Cable Crunch', 'Kneeling under a loaded cable lets you add external resistance to spinal flexion, progressively overloading the abs beyond what bodyweight crunches allow.'),
  ('Hanging Leg Raise', 'Hanging from a bar and raising the legs loads the lower abs and hip flexors while your grip and lats work isometrically to stabilize you.'),
  ('Toes to Bar', 'A more demanding hanging leg raise that adds momentum control and full hip flexion, building serious core and grip strength together.'),
  ('Ab Wheel Rollout', 'Rolling out from the knees forces the abs to resist spinal extension isometrically — one of the hardest anti-extension core exercises there is.'),
  ('Plank', 'An isometric hold that trains the entire core — abs, obliques, and lower back — to resist spinal extension and keep the body rigid.'),
  ('Mountain Climber', 'Driving the knees in from a plank position combines core anti-extension work with a cardio and hip-flexor component.'),
  ('Russian Twist', 'The rotational movement trains the obliques through trunk rotation, a pattern that straight-ahead ab exercises like crunches don''t touch.'),
  ('Side Plank', 'An isometric hold on one side that isolates the obliques and hip stabilizers to resist lateral flexion.')
) as v(name, why_effective)
where e.name = v.name;
