-- Adds beginner-oriented content to every exercise: the most common form
-- mistakes to watch for, and practical tips for someone doing the movement
-- for the first time. Run this in the Supabase SQL editor after 0001-0007.

alter table public.exercises
  add column if not exists common_mistakes text,
  add column if not exists beginner_tips text;

update public.exercises as e set
  common_mistakes = v.common_mistakes,
  beginner_tips = v.beginner_tips
from (values
  ('Barbell Curl',
   'Swinging the torso and using the hips to heave the bar up turns this into a momentum exercise instead of a biceps one, and letting the elbows drift forward reduces the stretch and shifts stress onto the shoulders.',
   'Start with an EZ-bar or dumbbells if a straight bar bothers your wrists, and use a weight you can lower for a full 2-3 second count — the biceps grow more from control than from how heavy the bar is.'),
  ('Cable Curl',
   'Standing too close to the machine shortens the range of motion, and leaning back at the top to "finish" the rep just swaps biceps tension for lower-back strain.',
   'Step back far enough that your arms hang fully extended at the bottom before you curl — that stretched starting position is where most of the growth stimulus comes from.'),
  ('Cable Overhead Tricep Extension',
   'Letting the elbows flare out to the sides turns this into a shoulder movement; keep them pointed forward and close to your head throughout.',
   'This one rewards a slow negative — lower the rope back to a full stretch behind your head before pressing out again, rather than bouncing at the bottom.'),
  ('Close-Grip Bench Press',
   'Gripping too narrow (hands touching) wrecks your wrists without adding triceps work — shoulder-width or just inside it is close enough.',
   'Keep your elbows tucked close to your ribs as you lower the bar, almost like a normal bench press but narrower — flaring them out shifts the work back to your chest.'),
  ('Concentration Curl',
   'Curling too fast and using your shoulder to help swing the weight up defeats the point of isolating one arm at a time.',
   'Brace your elbow firmly against the inside of your thigh and focus on squeezing the biceps hard at the top for a full second before lowering.'),
  ('Diamond Push-Up',
   'Letting the hips sag or pike up breaks the straight-body line and shifts load off the triceps and chest — brace your core like you''re holding a plank.',
   'If a full diamond push-up is too hard at first, do them from your knees or with your hands elevated on a bench until you build the strength.'),
  ('Dumbbell Kickback',
   'Swinging the dumbbell up using momentum instead of squeezing the triceps is the single most common mistake here — the weight should move slowly and under control.',
   'Keep your upper arm parallel to the floor and completely still; only your forearm should move. Lighter weight with a strict, full lockout beats a heavier weight swung into place.'),
  ('Hammer Curl',
   'Letting the wrist rotate at all during the curl turns it back into a regular curl and loses the brachialis/forearm emphasis that makes this variation useful.',
   'Keep your palms facing each other the entire rep, from the bottom stretch to the top squeeze, like you''re holding two hammers.'),
  ('Overhead Tricep Extension',
   'Letting the elbows flare wide instead of staying tucked near your ears shifts stress into the shoulder joint and reduces triceps tension.',
   'Use a lighter weight than you think you need at first — this is a stretched, vulnerable position for the elbow, and strict form matters more than load here.'),
  ('Preacher Curl',
   'Not lowering all the way down to a near-full elbow extension skips the hardest, most valuable part of the rep — the deep stretch at the bottom.',
   'Keep your upper arms glued to the pad the whole set; if your shoulders start lifting off, the weight is too heavy.'),
  ('Skull Crusher',
   'Letting the elbows flare outward as you lower the bar turns this into a shaky, unstable movement — keep them pointed at the ceiling and stationary.',
   'Lower the bar toward your forehead or just behind it, not straight down to your chest, and start with an empty bar or light dumbbells until you''re confident with the motion.'),
  ('Tricep Pushdown',
   'Leaning over the bar and using body weight to press it down is the most common cheat — keep your torso upright and let your triceps do the work.',
   'Keep your elbows pinned to your sides throughout; if they drift forward as you push down, you''re using your shoulders and chest more than your triceps.'),
  ('Zottman Curl',
   'Rotating your wrist too early (before you reach the top) or too late (after you''ve already started lowering) skips the part of the exercise that actually works the forearms.',
   'Slow down the lowering phase specifically — that pronated, palm-down descent is the whole point of this exercise, so don''t rush it.'),

  ('Barbell Row',
   'Rounding the lower back to heave the weight up is the most common and riskiest mistake — if your form breaks down, the weight is too heavy.',
   'Start lighter than you think you need and focus on keeping a flat back and hinged hips throughout; pulling the bar to your belly button, not your chest, keeps the lats doing the work.'),
  ('Cable Pullover',
   'Bending the elbows too much during the pull turns this into a lat pulldown variant instead of the straight-arm isolation it''s meant to be.',
   'Keep a slight, fixed bend in your elbows and focus on moving from the shoulder joint — think about pulling with your armpit, not your hands.'),
  ('Chest-Supported Row',
   'Using your arms to yank the weight rather than driving your elbows back and squeezing your shoulder blades together shortchanges the back muscles this is meant to target.',
   'Let your chest stay pinned to the pad the entire set — if you''re arching off it to move more weight, that''s a sign to drop the load.'),
  ('Chin-Up',
   'Using short, bouncy half-reps to rack up more reps skips the full range of motion — a real chin-up starts from a dead hang and finishes with your chin over the bar.',
   'If you can''t yet do a full rep, use a resistance band looped under your feet for assistance, or start with slow, controlled negatives (jump up, lower down slowly) to build the strength.'),
  ('Deadlift',
   'Rounding the lower back under load is the mistake that causes most deadlift injuries — keep your spine neutral from setup to lockout, even if it means using less weight.',
   'Start with light weight and focus entirely on the setup: bar over mid-foot, shins close to the bar, chest up, and hips pushed back before you even start pulling.'),
  ('Face Pull',
   'Pulling with straight arms and no external rotation turns this into a plain row and misses the rear delt and rotator cuff benefit that makes face pulls worthwhile.',
   'Pull the rope toward your face while rotating your hands so your thumbs end up pointing behind you — that external rotation is the whole point of the exercise.'),
  ('Inverted Row',
   'Letting your hips sag toward the floor turns this into an easier, less effective movement — keep your body in one straight line from head to heels.',
   'Make it easier by raising the bar higher (more upright body angle) or harder by lowering it and keeping your feet further out — adjust the angle to match your current strength.'),
  ('Lat Pulldown',
   'Leaning back excessively and yanking the bar down with body momentum turns this into a swinging motion instead of a controlled lat contraction.',
   'Pull your shoulder blades down and back before you even bend your elbows — thinking "elbows to your back pockets" helps keep the lats, not the arms, doing the work.'),
  ('Pendlay Row',
   'Not fully resetting the bar on the floor between reps (turning it into a continuous "touch and go" row) defeats the point of this strict, dead-stop variation.',
   'Keep your torso close to parallel with the floor throughout — if you''re standing up more with each rep, the weight is too heavy to keep in check.'),
  ('Pull-Up',
   'Kipping or swinging your legs to generate momentum turns a pull-up into a completely different, much easier exercise — a strict pull-up should start and end fully still.',
   'Build toward a full pull-up with assisted variations (a resistance band, an assisted pull-up machine, or slow negatives from a box) rather than grinding through partial reps.'),
  ('Rack Pull',
   'Setting the pins too low so the exercise turns into a nearly full deadlift removes the point of overloading the top-range lockout specifically.',
   'Set the bar around knee height to start, and prioritize a strong, controlled lockout with your shoulders back rather than just moving as much weight as possible.'),
  ('Seated Cable Row',
   'Rounding your back forward to reach further at the start, or leaning back excessively to finish the pull, both turn this into a lower-back exercise instead of a back-thickness one.',
   'Keep your torso mostly upright and stable throughout the set — the movement should come from your arms and shoulder blades, not from rocking your torso back and forth.'),
  ('Single-Arm Dumbbell Row',
   'Rotating your torso to help heave the dumbbell up uses momentum instead of the lat — keep your hips and shoulders square to the bench.',
   'Let the dumbbell hang and stretch down fully at the bottom of each rep before pulling — a rushed, partial range of motion is the most common way people shortchange this exercise.'),
  ('Straight-Arm Pulldown',
   'Bending the elbows during the pull turns this into a pulldown variation and takes tension off the lats, which is the entire point of doing it with straight arms.',
   'Keep a slight, fixed elbow bend throughout and think about pulling the bar down with your lats by driving your upper arms toward your body, not your hands toward the floor.'),
  ('T-Bar Row',
   'Using your lower back to jerk the weight up instead of hinging at the hips and pulling with your back is the most common way people get hurt on this exercise.',
   'Keep your chest up and back flat throughout, and pull the handle to your lower chest/upper stomach rather than trying to touch it to your chin.'),

  ('Barbell Bench Press',
   'Bouncing the bar off your chest and flaring your elbows out to 90 degrees both increase shoulder injury risk without adding to the lift — lower with control and keep elbows at roughly a 45-degree angle to your torso.',
   'Always use a spotter or safety bars when pushing heavy weight, and don''t be afraid to start with just the bar to groove the movement pattern before adding plates.'),
  ('Cable Chest Fly',
   'Bending the elbows too much turns this into a press instead of a fly — keep a slight, fixed bend and let the movement come from your shoulder joint.',
   'Set the cables at chest height to start and focus on squeezing your chest together at the finish rather than how far you can bring the handles.'),
  ('Decline Barbell Press',
   'Lowering the bar too high on the chest (near the collarbone) works against the decline angle — bring it to your lower chest instead.',
   'Have a spotter present or use a machine version if you''re new to decline pressing — being upside-down under a loaded bar is more disorienting than flat benching.'),
  ('Dips',
   'Going too deep with poor shoulder mobility can strain the shoulder joint — if you feel pinching at the bottom, don''t go as low.',
   'Lean your torso forward for more chest emphasis, or stay upright for more triceps focus; use an assisted dip machine or resistance band if bodyweight dips are too hard at first.'),
  ('Dumbbell Fly',
   'Bending the elbows too much turns this into a press, and lowering the dumbbells too far past shoulder level can strain the shoulder joint.',
   'Keep a soft, fixed bend in your elbows throughout and go only as low as feels comfortable in your shoulders — the stretch should feel like a pull across your chest, not a strain.'),
  ('Flat Dumbbell Press',
   'Letting the dumbbells drift too far out to the sides at the bottom puts unnecessary strain on the shoulder joint.',
   'Start with lighter dumbbells than you''d use on a barbell — stabilizing two independent weights is harder than it looks, especially at the bottom of the rep.'),
  ('Incline Barbell Press',
   'Setting the bench too steep turns this into more of a shoulder press than a chest exercise — a 30-45 degree incline is the sweet spot for upper chest emphasis.',
   'Lower the bar to your upper chest, not your neck, and expect to use less weight than on a flat bench press — that''s normal, not a sign you''re doing it wrong.'),
  ('Incline Cable Fly',
   'Setting the cable angle too low relative to the bench angle reduces the upper-chest stretch that this exercise is meant to create.',
   'Focus on squeezing your chest at the top of the rep and controlling the stretch at the bottom rather than rushing through reps.'),
  ('Incline Dumbbell Press',
   'Pressing the dumbbells too far back toward your face instead of up and slightly forward reduces chest engagement and adds shoulder strain.',
   'A 30-degree incline is plenty — steeper benches shift the work toward your shoulders more than your chest.'),
  ('Landmine Press',
   'Standing too upright and pressing straight overhead defeats the shoulder-friendly angle that makes this exercise useful — let the bar path angle naturally up and away from your shoulder.',
   'This is a great option if regular overhead or bench pressing bothers your shoulders — start light and get a feel for the diagonal pressing path before adding weight.'),
  ('Machine Chest Press',
   'Setting the seat height wrong so the handles line up with your neck or stomach instead of your mid-chest reduces how effectively the machine targets your chest.',
   'Adjust the seat so the handles are level with your chest before you start, and use this machine to safely push close to failure since there''s no risk of being pinned like with a barbell.'),
  ('Pec Deck',
   'Letting your elbows drop too low or using momentum to swing the handles together reduces chest tension and adds shoulder strain.',
   'Keep your elbows roughly at shoulder height throughout and focus on a slow squeeze at the point where your hands come together.'),
  ('Push-Up',
   'Letting the hips sag or piking the hips up breaks the straight-body plank position this exercise relies on.',
   'If a full push-up is too hard, do them from your knees or with your hands elevated on a bench or step — both are legitimate ways to build up to a full push-up, not a lesser version of it.'),
  ('Svend Press',
   'Letting the plates separate or losing the squeeze between your palms removes the isometric tension that makes this exercise work.',
   'Use a lighter, easier-to-grip plate to start (a 5-10 lb plate is often enough) — the point is the squeeze, not the weight.'),

  ('Ab Wheel Rollout',
   'Letting your lower back arch and sag toward the floor as you roll out is the most common mistake and the one most likely to strain your back — only roll out as far as you can while keeping your core braced.',
   'Start from your knees, not your feet, and only roll out a short distance until you build the strength to go further — this is a much harder exercise than it looks.'),
  ('Bicycle Crunch',
   'Pulling on your neck with your hands instead of using your abs to rotate is a common way people strain their neck on this exercise.',
   'Move slowly and with control rather than cycling quickly — a slower pace with a real rotation and extension works the obliques and abs far better than a fast, sloppy pace.'),
  ('Cable Crunch',
   'Pulling with your arms instead of curling your torso down using your abs turns this into an arm exercise instead of a weighted ab exercise.',
   'Keep your hips still and focus on rounding your spine forward from your ribcage — the movement should come from flexing your torso, not from your hips or arms.'),
  ('Dead Bug',
   'Letting your lower back arch off the floor as you extend your arm and leg is the exact thing this exercise is supposed to train you out of — press your lower back into the floor throughout.',
   'Move slowly and only extend your arm and leg as far as you can while keeping your lower back flat — this is about control, not range of motion.'),
  ('Hanging Leg Raise',
   'Swinging your body to generate momentum instead of using your abs to lift your legs turns this into a much less effective exercise.',
   'If a straight-leg raise is too hard at first, bend your knees and raise them toward your chest instead — that''s a legitimate, easier variation, not a lesser version.'),
  ('Mountain Climber',
   'Letting your hips rise up into a piked position instead of staying low in a plank line reduces the core and cardio benefit of the exercise.',
   'Slow down if your hips are bouncing around — a controlled pace with good plank form beats a fast, sloppy one for both your core and your safety.'),
  ('Pallof Press',
   'Rotating your torso as you press out (letting the cable win) defeats the entire point of this anti-rotation exercise — you should feel your core resisting the pull, not giving into it.',
   'Start with a lighter weight than feels challenging and stand further from the machine to increase the angle of pull — this exercise is about resisting rotation, not moving weight.'),
  ('Plank',
   'Letting your hips sag toward the floor or piking them up into the air are the two most common form breakdowns — your body should form one straight line from head to heels.',
   'Focus on quality over duration — a strict 30-second plank is more valuable than a 2-minute plank with your hips sagging halfway through.'),
  ('Russian Twist',
   'Moving your arms without actually rotating your torso, or rushing through reps without control, both reduce how much the obliques are actually working.',
   'Keep your feet on the floor at first if lifting them (for extra difficulty) causes your lower back to round — build up to the harder version once your core is stronger.'),
  ('Side Plank',
   'Letting your hips drop toward the floor or rotating your torso forward or backward both reduce the oblique engagement this exercise is meant to create.',
   'Stack your feet, hips, and shoulders in one straight line and focus on lifting your hips as high as comfortably possible — a shorter hold with good form beats a longer one with sagging hips.'),
  ('Sit-Up',
   'Yanking on your neck with your hands or using momentum to fling your torso up both reduce how much your abs actually do the work.',
   'Cross your arms over your chest instead of putting your hands behind your head, which removes the temptation to pull on your neck.'),
  ('Toes to Bar',
   'Excessive swinging (kipping) to fling your legs up before you have the strict strength to do so is the most common way people injure their shoulders on this exercise.',
   'Master strict hanging leg raises first, then build toward toes-to-bar — this is one of the more advanced core exercises and there''s no shame in scaling it down.'),

  ('Barbell Back Squat',
   'Letting your knees cave inward or your heels lift off the floor are the two most common form breaks, and both usually mean the weight is too heavy or your depth is too deep for your current mobility.',
   'Practice with just the bar (or even no bar at all) until you can squat to depth with your chest up and heels down — squat depth and weight should build up together, not weight first.'),
  ('Bulgarian Split Squat',
   'Putting too much weight on your front foot''s toes instead of the whole foot, or letting your front knee cave inward, are common issues that show up especially as the weight gets heavier.',
   'Start with just your bodyweight or light dumbbells — the balance demand of this exercise is challenging on its own before you add real load.'),
  ('Front Squat',
   'Letting your elbows drop, which causes the bar to roll forward and your torso to collapse, is the most common issue — keep your elbows up and pointed forward throughout.',
   'If the front rack position feels uncomfortable on your wrists, try a cross-arm grip instead of the standard clean grip until your wrist mobility improves.'),
  ('Glute Bridge',
   'Arching your lower back to gain extra height instead of squeezing your glutes is the most common mistake — the movement should come from your hips, not your spine.',
   'Pause and squeeze your glutes hard for a full second at the top of each rep — this is a simple exercise, but that pause is what makes it effective.'),
  ('Goblet Squat',
   'Letting your elbows get squeezed by your knees as you descend (a sign you''re not sitting back enough) usually means your torso is too upright or your depth is off.',
   'This is one of the best squat variations to learn the pattern with — holding the weight in front naturally encourages an upright torso and good depth.'),
  ('Hack Squat',
   'Placing your feet too high or too low on the platform changes which muscles do the work — too high shifts to your glutes and hamstrings, too low can stress your knees.',
   'Start with a foot position in the middle of the platform and adjust from there based on comfort — there''s no single "correct" foot placement, just what feels safe for your knees.'),
  ('Hip Adduction Machine',
   'Using a jerky, fast pace instead of a controlled squeeze reduces how much the adductors actually work.',
   'This is a good exercise to focus purely on feeling the muscle work — use a moderate weight and squeeze your inner thighs together deliberately rather than just moving the pads.'),
  ('Hip Thrust',
   'Hyperextending your lower back at the top instead of stopping when your body forms a straight line from shoulders to knees is the most common mistake, and it can strain your lower back over time.',
   'Start with just your bodyweight or a light barbell to learn the hip hinge pattern before adding significant weight — a barbell pad for your hips is worth using once you do add weight.'),
  ('Leg Extension',
   'Using momentum to fling the weight up instead of a controlled extension reduces the quad isolation this exercise is meant to provide.',
   'Pause and squeeze your quads at the top of each rep, and lower the weight slowly — this exercise rewards control much more than heavy weight.'),
  ('Leg Press',
   'Letting your lower back round and lift off the pad (usually from going too deep or using too much weight) can strain your lower back even though it doesn''t feel like a back exercise.',
   'Keep your lower back flat against the pad throughout the set — if it starts to round, that''s your cue to reduce the depth or the weight.'),
  ('Lying Leg Curl',
   'Arching your hips up off the pad to help move the weight reduces hamstring isolation and adds unnecessary lower-back strain.',
   'Keep your hips pressed into the pad throughout the set, and squeeze your hamstrings hard at the top of the curl before lowering slowly.'),
  ('Nordic Hamstring Curl',
   'Dropping too fast instead of resisting the descent with your hamstrings defeats the entire purpose of this exercise — the slow, controlled lowering is the whole point.',
   'This is a genuinely difficult exercise even for experienced lifters — start with a small range of motion and a partner or anchor to hold your ankles, and don''t be discouraged if you can only lower a few inches at first.'),
  ('Romanian Deadlift',
   'Rounding your lower back or bending your knees too much (turning it into a regular deadlift) both reduce the hamstring stretch this exercise is meant to create.',
   'Keep the bar close to your legs as it travels down, and only lower it as far as you can while keeping your back flat — that''s usually around shin or mid-calf height, not the floor.'),
  ('Seated Calf Raise',
   'Using a bouncy, fast pace instead of a full stretch and a full contraction reduces how much the soleus actually works.',
   'Pause briefly at the bottom stretch and squeeze at the top — calves respond well to higher reps and a slow tempo, so don''t rush the set.'),
  ('Standing Calf Raise',
   'Using a short, bouncy range of motion instead of a full stretch at the bottom and a full rise onto your toes shortchanges the exercise significantly.',
   'Slow down and pause at the top of each rep — calves are a stubborn muscle group for most people, and strict form over time matters more than the weight used.'),
  ('Step-Up',
   'Pushing off with your back leg instead of driving entirely through the front leg on the box reduces how much work your working leg actually does.',
   'Start with a lower box height than feels challenging and increase it as your balance and strength improve — a box around knee height is a good starting point for most people.'),
  ('Sumo Deadlift',
   'Letting your knees cave inward as you stand up is the most common issue with the wide stance — actively push your knees out in the direction of your toes throughout the lift.',
   'Spend time finding a stance width and toe angle that lets you get your hips low with a flat back before adding weight — the right stance varies more person to person than with a conventional deadlift.'),
  ('Walking Lunge',
   'Taking too short a step, which puts excess stress on your front knee, is the most common mistake — a longer step keeps your knee from traveling too far past your toes.',
   'Start without weight and focus on balance and a controlled descent before adding dumbbells — this exercise challenges stability more than most other leg exercises.'),

  ('Arnold Press',
   'Rushing through the rotation instead of controlling it throughout the press turns this into a regular shoulder press and loses the extra range of motion that makes it useful.',
   'Use lighter dumbbells than you would for a regular shoulder press at first — the rotating path is more demanding on the shoulder joint than it looks.'),
  ('Cable Front Raise',
   'Using momentum to swing the handle up instead of a slow, controlled raise reduces anterior deltoid engagement significantly.',
   'Keep a very slight bend in your elbow and raise to about shoulder height — going higher doesn''t add benefit and just adds strain.'),
  ('Cable Lateral Raise',
   'Shrugging your shoulder up toward your ear as you raise the handle shifts work from your side delt to your traps.',
   'Keep your shoulder pressed down away from your ear throughout the movement, and use a lighter weight than you''d think — strict form matters much more than load for lateral raises.'),
  ('Cuban Press',
   'Rushing through the sequence instead of pausing briefly at each position (row, rotation, press) reduces the shoulder stability benefit this exercise is meant to provide.',
   'Use light weight, even lighter than you''d use for a regular lateral raise — this exercise is about control and shoulder health, not moving heavy weight.'),
  ('Dumbbell Shoulder Press',
   'Arching your lower back excessively to press the weight up is a common compensation when the weight is too heavy — keep your core braced and your back neutral.',
   'Press the dumbbells up and slightly inward rather than straight up and out to the sides — that path is more natural for the shoulder joint.'),
  ('Front Raise',
   'Swinging the weight up using your lower back and hips instead of your shoulder is the most common mistake, especially as fatigue sets in.',
   'Raise the weight only to about shoulder height, not higher — going overhead doesn''t add benefit and shifts strain onto the shoulder joint.'),
  ('Lateral Raise',
   'Using too much weight and swinging it up with momentum is extremely common on this exercise — lateral raises should be done light and strict.',
   'Lead with your elbows, not your hands, and stop at shoulder height — this exercise is far more effective done light and controlled than heavy and sloppy.'),
  ('Overhead Press',
   'Arching your lower back excessively to press the bar overhead is a common compensation for tight shoulders or a weight that''s too heavy.',
   'Brace your core hard before each rep and press the bar in a path close to your face rather than out and around it — start with a weight that lets you keep your ribs down and core tight.'),
  ('Rear Delt Fly',
   'Using momentum to swing the dumbbells up instead of squeezing your shoulder blades together reduces how much your rear delts actually work.',
   'Hinge forward more than feels natural at first (roughly parallel to the floor) — a more upright torso turns this into a shrug instead of a rear delt exercise.'),
  ('Reverse Pec Deck',
   'Using too much weight and letting your arms bend more than intended turns this into a pulling exercise instead of an isolated rear delt one.',
   'Keep a slight, fixed bend in your elbows and focus on squeezing your shoulder blades together at the back of the movement.'),
  ('Shrug',
   'Rolling your shoulders in a circular motion instead of moving them straight up and down doesn''t add benefit and can irritate the shoulder joint.',
   'Move your shoulders straight up toward your ears and hold the squeeze for a second at the top — you don''t need to roll them, despite what you might see others do.'),
  ('Upright Row',
   'Pulling the bar too high (above chest height) with elbows flared out is a common cause of shoulder impingement on this exercise.',
   'Stop pulling when your elbows reach about shoulder height, and consider a wider grip if you feel any pinching in the front of your shoulders.')
) as v(name, common_mistakes, beginner_tips)
where e.name = v.name;
